services:
  nginx:
    image: nginx:latest
    container_name: neville
    ports:
      - 8042:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
      - ./logs:/var/log/nginx/
  
  php-fpm:
    image: php:8-fpm
    volumes:
    - ./:/var/www/
    - ./logs/php.log:/var/log/fpm-php.www.log